[tool.poetry]
name = "airflow"
version = "0.1.0"
description = ""
authors = ["Gustavo Paulino <Guh.Naasc@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
